#!/usr/bin/env php
<?php

require_once __DIR__ . '/vendor/autoload.php';

use Steve\Renamespacer\Document;
use Steve\Renamespacer\Fixer;
use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\Finder\Finder;

$fs = new Filesystem();
$args = $_SERVER['argv'];

if (count($args) != 2) {
    echo 'No subject provided', PHP_EOL;
    exit;
}

$src = $args[1];
$dst = __DIR__ . '/dst/' . basename($src);

$fs->remove($dst);
$fs->mirror($src, $dst);

$fixer = new Fixer();

foreach (Finder::create()->files()->in($dst)->name('*.php') as $file) {
    echo $file->getRelativePathname(), PHP_EOL;

    $document = new Document($file->getContents());

    $fixer->fix($document);

    $fs->dumpFile($file->getRealpath(), (string) $document);
}
