#!/usr/bin/env php
<?php

require_once __DIR__ . '/vendor/autoload.php';

use Steve\Renamespacer\Document;
use Steve\Renamespacer\Fixer;
use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\Finder\Finder;

$fs = new Filesystem();
$args = $_SERVER['argv'];

if (count($args) != 2) {
    echo 'No subject provided', PHP_EOL;
    exit;
}

$src = $args[1];
$dst = __DIR__ . '/dst/' . basename($src);

$fs->remove($dst);
$fs->mirror($src, $dst);

$documents = [];
$fixer = new Fixer();

foreach (Finder::create()->files()->in($dst)->name('*.php') as $file) {
    $document = $documents[] = new Document($file);

    $fixer->fix($document);

    $fs->dumpFile($file->getRealpath(), (string) $document);

    echo '.';
}

$count = count($documents);

$multiples = array_filter($documents, function ($document) {
    return count($document->getNamespaces()) > 1;
});

if ($multiples) {
    echo '

multiple namespace candidates found in:

';

    echo implode(PHP_EOL, array_map(
        function ($document) {
            return $document->getFile()->getRelativePathname();
        },
        $multiples
    ));
}

echo '

--

' . $count . ' files processed

done, review any problems above and run your tests
';
